trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
   npm install
  displayName: 'npm install'

- bash: |
   npx hexo generate
  displayName: 'hexo generate'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/public'
    ArtifactName: 'drop'
    publishLocation: 'Container'