# chan theme configuration

# site setting
rss: /atom.xml

# style setting
monochrome: true

# view setting
avatar: /files/avatar/round-color-300.png
avatarLink: /about
maxContentWidth: 1000px # set the main content column's max-width property. keep it blank to unlimited the width
copyright: # the copyright text in the footer, could be richtext

# sidebar navigator structure
# It's a list with item that is also list.
# The item of first level list means a group of links,
# and the item of the second level list means exactly a link.
# A link item is an object whit two properties: 'name' for displaying and 'link' for redirecting.
# A link starts with http/https would be rendered as a tag with 'target="_blank"' .
# There are also some special link items representing in string: 'categories', 'tags' and 'archives'
nav:
  -
    -
      name: Content
      url: '/'
    -
      name: About Me
      url: '/about'
    -
      name: Presentations
      url: '/presentations'
  -
    - categories
    - tags
    - archives

social:
  -
    -
      name: Twitter
      url: http://twitter.com/codefoster
      image: /images/social-icons/twitter.png
    -
      name: GitHub
      url: https://github.com/codefoster
      image: /images/social-icons/github.png
    -
      name: LinkedIn
      url: https://linkedin.com/in/codefoster
      image: /images/social-icons/linkedin.png
    -
      name: Skype
      url: skype:jeremyrfoster?chat
      image: /images/social-icons/skype.png
    -
      name: Channel9
      url: https://channel9.msdn.com/niners/codefoster
      image: /images/social-icons/ch9.png
    -
      name: Email
      url: mailto:jeremy.foster@microsoft.com
      image: /images/social-icons/email.png
    -
      name: RSS
      url: /atom.xml
      image: /images/social-icons/rss.png

# open graph
twitter: codefoster
cc: none

# FancyBox / PhotoSwipe
# Although it is called fancybox, we use PhotoSwipe instead.
# Check http://photoswipe.com
fancybox: true    # enable fancybox/photoswipe rendering
# photoswipe: true  # the same
